import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";
import Image from "next/image";

import Button from "~/component/Button";
import FormGroup from "~/component/FormGroup";
import Input from "~/component/Input";
import { api } from "~/utils/api";
import { env } from "~/env.mjs";

const GeneratePage: NextPage = () => {
  const [form, setForm] = useState({
    prompt: "",
  });

  const [imageUrl, setImageUrl] = useState("");

  function updateForm(key: string) {
    return function (e: React.ChangeEvent<HTMLInputElement>) {
      setForm((prev) => ({
        ...prev,
        [key]: e.target.value,
      }));
    };
  }

  const generateIcon = api.generate.generateIcon.useMutation({
    onSuccess(data) {
      console.log("mutation finished", data.imageUrl);
      if (!data.imageUrl) return;
      setImageUrl(data.imageUrl);
    },
  });
  function handleFormSubmit(e: React.FormEvent) {
    e.preventDefault();
    // TODO: submit form data to backend

    generateIcon.mutate({
      prompt: form.prompt,
    });
    setForm({ prompt: "" });
  }

  const session = useSession();
  const isLoggedIn = !!session.data;

  return (
    <>
      <Head>
        <title>Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {!isLoggedIn && (
          <Button
            onClick={() => {
              signIn().catch(console.error);
            }}
          >
            Login
          </Button>
        )}
        {isLoggedIn && (
          <Button
            onClick={() => {
              signOut().catch(console.error);
            }}
          >
            Logout
          </Button>
        )}
        {session.data?.user.name}
        <form onSubmit={handleFormSubmit}>
          <FormGroup>
            <label>Prompt</label>
            <Input onChange={updateForm("prompt")} />
            <Button>Submit</Button>
          </FormGroup>
        </form>

        <Image
          alt="an image of your generated prompt"
          height={200}
          width={200}
          src={imageUrl}
        />
      </main>
    </>
  );
};

export default GeneratePage;
